import React from "react";
import {
  Flex,
  Box,
  FormControl,
  FormLabel,
  Input,
  Checkbox,
  Stack,
  Button,
  Heading,
  Text,
  useColorModeValue,
  useBreakpointValue,
} from "@chakra-ui/react";

import Link from "next/link";

import Head from "next/head";
import FloatingButton from "../../components/FloatingButton";
import { useRouter } from "next/router";
import { useFormik } from "formik";
import { SiEclipseche } from "react-icons/si";
import helpers from "../../helpers";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthContext } from "../../context/auth";

export default function Login() {
  const [isLoading, setIsLoading] = React.useState(false);
  const authContext = React.useContext(AuthContext);
  const router = useRouter();

  const notify = (msg, type) =>
    toast(msg, {
      type,
      position: "top-center",
      autoClose: 5000,
      hideProgressBar: true,
    });

  const formik = useFormik({
    initialValues: {
      email: "",
      password: "",
    },

    onSubmit: async (values) => {
      setIsLoading(true);
      try {
        const res = await helpers.login(values).then((data) => {
          if (data.name === "AxiosError") {
            notify("Wrong email or password", "error");
          } else {
            notify("Authentication successful!", "success");
            authContext.setUserAuthInfo(data.data.token);
            console.log("saving credentials...", data.data.data)
            authContext.setUserDetails(data.data.data);
            router.push("/app");
          }
        });
      } catch (error) {
        console.log(error);
      } finally {
        setIsLoading(false);
      }
    },
  });

  return (
    <>
      <Head>
        <title>Login - Expert Hub Trade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        minH={"100vh"}
        align={"center"}
        justify={"center"}
        bg={useColorModeValue("#131722", "gray.800")}
      >
        <ToastContainer />

        <Stack spacing={4} mx={"auto"} w={"lg"} py={12} px={6}>
          <Stack align={"center"}>
            <SiEclipseche size={40} color="#4299e1" />
          </Stack>
          <Box
            rounded={"md"}
            bg={useColorModeValue("white", "gray.700")}
            // boxShadow={"lg"}
            w={{ base: "100%", md: "100%" }}
            p={8}
          >
            <form onSubmit={formik.handleSubmit}>
              <Stack spacing={4}>
                <FormControl id="email">
                  <FormLabel fontWeight="normal">Email address</FormLabel>
                  <Input
                    p={"6"}
                    id="email"
                    name="email"
                    type="email"
                    onChange={formik.handleChange}
                    value={formik.values.email}
                  />
                </FormControl>
                <FormControl id="password">
                  <FormLabel fontWeight="normal">Password</FormLabel>
                  <Input
                    p={6}
                    id="password"
                    name="password"
                    type="password"
                    onChange={formik.handleChange}
                    value={formik.values.password}
                  />
                </FormControl>
                <Stack spacing={10}>
                  <Button
                    bg={"blue.400"}
                    color={"white"}
                    fontWeight="normal"
                    type="submit"
                    mt={6}
                    p={6}
                    isLoading={isLoading}
                    // h={10}
                    _hover={{
                      bg: "blue.500",
                    }}
                  >
                    Login to your account
                  </Button>
                </Stack>
                <br />
                <Link color={"blue.400"} href="/account/signup">Forgot password?</Link>
                <Text fontWeight="normal">
                  Don&apos;t have an account?{" "}
                  <Link href="/account/signup" color={"blue.400"}>
                    Signup
                  </Link>
                </Text>
              </Stack>
            </form>
          </Box>
        </Stack>
      </Flex>

      <FloatingButton />
    </>
  );
}
