import React from "react";
import Head from "next/head";
import DashboardWrapper from "../../components/app/DashboardWrapper";
import FloatingButton from "../../components/FloatingButton";
import {
  Box,
  Heading,
  Text,
  SimpleGrid,
  Icon,
  Stack,
  Flex,
  Select,
  useColorModeValue,
  Button,
  FormControl,
  FormLabel,
  Input,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
  useDisclosure,
} from "@chakra-ui/react";
import WithAuth from "../../HOCs/WithAuth";
import { useFormik } from "formik";
import { useRouter } from "next/router";

function Deposit() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const router = useRouter();

  const formik = useFormik({
    initialValues: {
      amount: "",
    },

    onSubmit: (values) => {
      router.push(
        {
          pathname: "/app/payment",
          query: {
            amount: values.amount,
          },
        },
        "/app/payment"
      );
    },
  });

  return (
    <div>
      <DashboardWrapper>
        <Head>
          <title>Dashboard - Expert Hub Trade</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Heading
          lineHeight={"110%"}
          fontSize={{ base: "2xl", sm: "2xl", md: "2xl" }}
          mb={5}
          color="white"
          fontWeight="normal"
          textTransform="uppercase"
          letterSpacing="2px"
          mt={5}
        >
          <Text>Your deposits</Text>
        </Heading>

        <Button
          color={"blue.800"}
          bg="linear-gradient(90deg,#40efeb,#7edb92)"
          //   rounded={"full"}
          // px={12}
          // py={8}
          my={5}
          size="md"
          // fontWeight="medium"
          // fontSize="md"
          onClick={onOpen}
        >
          New Deposit
        </Button>

        <Modal onClose={onClose} isOpen={isOpen} isCentered>
          <ModalOverlay />
          <ModalContent>
            <form onSubmit={formik.handleSubmit}>
              <ModalHeader fontWeight="normal">Make new deposit</ModalHeader>
              <ModalCloseButton />
              <ModalBody>
                <Stack spacing={4}>
                  <FormControl id="amount">
                    <Input
                      type="text"
                      p={"6"}
                      id="amount"
                      name="amount"
                      onChange={formik.handleChange}
                      placeholder="Enter amount here"
                      onChange={formik.handleChange}
                      value={formik.values.amount}
                    />
                  </FormControl>
                </Stack>
              </ModalBody>

              <ModalFooter>
                <Button
                  onClick={onClose}
                  colorScheme="green"
                  mr={2}
                  fontWeight="normal"
                  type="submit"
                >
                  Continue
                </Button>
                <Button onClick={onClose} colorScheme="red" fontWeight="normal">
                  Close
                </Button>
              </ModalFooter>
            </form>
          </ModalContent>
        </Modal>
      </DashboardWrapper>

      <FloatingButton />
    </div>
  );
}

export default WithAuth(Deposit);
