import React from "react";
import Head from "next/head";
import DashboardWrapper from "../../components/app/DashboardWrapper";
import { Box, Heading, Text, Link, Center, Button } from "@chakra-ui/react";
import FloatingButton from "../../components/FloatingButton";
import { SiTelegram } from "react-icons/si";
import WithAuth from "../../HOCs/WithAuth";

function Support() {
  return (
    <>
      <DashboardWrapper>
        <Head>
          <title>Dashboard - Legit Crypto Option</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Box
          maxW="7xl"
          mx={"auto"}
          pt={5}
          px={{ base: 2, sm: 12, md: 17 }}
          textAlign="center"
          color="white"
        >
          <Heading
            lineHeight={"110%"}
            fontSize={{ base: "2xl", sm: "4xl", md: "4xl" }}
            fontFamily="inherit"
          >
            Legit Crypto Option Support
          </Heading>
          <Text mt={2}>
            For inquiries, suggestions or complains. Mail us at:
            <Link href="/" color="blue.400">
              {" "}
              support@legitcryptooption.org
            </Link>
          </Text>

          <Center p={8}>
            <Button
              w={"full"}
              maxW={"md"}
              colorScheme={"telegram"}
              leftIcon={<SiTelegram />}
              as="a"
              href="https://t.me/MAX_PROFITFX"
            >
              <Center>
                <Text>Join our telegram</Text>
              </Center>
            </Button>
          </Center>
        </Box>
      </DashboardWrapper>

      <FloatingButton />
    </>
  );
}

export default WithAuth(Support);
