import React from "react";
import Head from "next/head";
import DashboardWrapper from "../../components/app/DashboardWrapper";
import {
  Box,
  useColorModeValue,
  Heading,
  Text,
  Table,
  TableContainer,
  Tr,
  Td,
  Th,
  Tbody,
  Thead,
  Tfoot,
} from "@chakra-ui/react";
import FloatingButton from "../../components/FloatingButton";
import WithAuth from "../../HOCs/WithAuth";

function Transactions() {
  return (
    <div>
      <DashboardWrapper>
        <Head>
          <title>Dashboard - Expert Hub Trade</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Heading
          lineHeight={"110%"}
          fontSize={{ base: "2xl", sm: "4xl", md: "4xl" }}
          mb={5}
          color="white"
        >
          <Text>Transaction History</Text>
        </Heading>
        <Box
          h={"fit-content"}
          px={{ base: 2, md: 4 }}
          py={"5"}
          shadow={"xl"}
          //   border={"1px solid"}
          borderColor={useColorModeValue("gray.800", "gray.500")}
          rounded={"lg"}
          bg="white"
        >
          <TableContainer>
            <Table size="sm">
              <Thead>
                <Tr>
                  <Th>Amount</Th>
                  <Th>Status</Th>
                  <Th isNumeric>Date</Th>
                </Tr>
              </Thead>
              <Tbody>
                <Tr>
                  <Td></Td>
                  <Td></Td>
                  <Td isNumeric></Td>
                </Tr>
              </Tbody>
            </Table>
          </TableContainer>
        </Box>
      </DashboardWrapper>

      <FloatingButton />
    </div>
  );
}

export default WithAuth(Transactions);
