import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";

import {
  Box,
  Heading,
  Container,
  Text,
  Button,
  SimpleGrid,
  Icon,
  useColorModeValue,
  createIcon,
  Stack,
  HStack,
  VStack,
  Center,
  Flex,
  Image as ChakraImage,
} from "@chakra-ui/react";
import Image from "next/image";
import CountUp from "react-countup";

import { secure, scroll, exchange, laptop, pattern } from "../assets/list";
import Pricing from "../components/Pricing";
import Footer from "../components/Footer";
import Testimonials from "../components/Testimonials";
import { TickerTape, CryptoCurrencyMarket } from "react-ts-tradingview-widgets";
import FloatingButton from "../components/FloatingButton";

import patterns from "../assets/images/wavyLines.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Expert Hub Trade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <TickerTape colorTheme="dark"></TickerTape>
      <Hero />

      <Container maxW={{ md: "80%", base: "90%" }} overflow="hidden">
        <CryptoCurrencyMarket
          colorTheme="dark"
          width="100%"
          height={400}
        ></CryptoCurrencyMarket>
      </Container>

      <Box p={4} mt={"36"}>
        <Stack spacing={4} as={Container} maxW={"3xl"} textAlign={"center"}>
          <Heading
            lineHeight={"110%"}
            fontSize={{ base: "2xl", sm: "4xl", md: "4xl" }}
          >
            <Text>The most trusted cryptocurrency platform</Text>
          </Heading>
          <Text color={"gray.600"} mt={10}>
            Here are a few reasons why you should choose Expert Hub Trade
          </Text>
        </Stack>

        <Container maxW={"6xl"} mt={10}>
          <SimpleGrid columns={{ base: 1, md: 2, lg: 3 }} spacing={10}>
            <Box>
              <Image src={secure} alt="" />
              <Text fontWeight={600} color={"blue.400"} my={"2"}>
                Secure storage
              </Text>
              <Text color={"gray.600"}>
                We store the vast majority of the digital assets in secure
                offline storage.
              </Text>
            </Box>

            <Box>
              <Image src={scroll} alt="" />
              <Text fontWeight={600} color={"blue.400"} my={"2"}>
                Protected by insurance
              </Text>
              <Text color={"gray.600"}>
                Expert Hub Trade maintains crypto insurance and all USD cash
                balances are covered by FDIC insurance, up to a maximum of
                $250,000.
              </Text>
            </Box>

            <Box>
              <Image src={exchange} alt="" />
              <Text fontWeight={600} color={"blue.400"} my={"2"}>
                Industry best practices
              </Text>
              <Text color={"gray.600"}>
                Expert Hub Trade supports a variety of the most popular digital
                currencies.
              </Text>
            </Box>
          </SimpleGrid>

          <Center mt={36}>
            <ChakraImage
              src={
                "https://empiretradesfx.com/wp-content/uploads/2021/05/Asset-1mockup-1.png"
              }
            />
          </Center>
        </Container>
      </Box>

      <Box bg="blue.400" my={36} h={{ md: "2xs", base: "xl" }} id="stats">
        <Flex alignItems="center" justifyContent="center" h="inherit">
          <Container maxW={{ md: "80%", base: "90%" }}>
            <SimpleGrid
              columns={{ base: 1, md: 2, lg: 3 }}
              spacing={10}
              color="white"
            >
              <Box textAlign="center">
                <Text
                  fontWeight={600}
                  my={"2"}
                  fontSize={{ base: "4xl" }}
                  lineHeight={"110%"}
                  textAlign="center"
                >
                  <CountUp start={0} end={6000} /> +
                </Text>
                <Text textAlign="center">Profitable trades</Text>
              </Box>

              <Box>
                <Text
                  fontWeight={600}
                  my={"2"}
                  fontSize={{ base: "4xl" }}
                  lineHeight={"110%"}
                  textAlign="center"
                >
                  $
                  <CountUp start={0} end={20} />M
                </Text>
                <Text textAlign="center">Quarterly volume traded</Text>
              </Box>

              <Box>
                <Text
                  fontWeight={600}
                  my={"2"}
                  fontSize={{ base: "4xl" }}
                  lineHeight={"110%"}
                  textAlign="center"
                >
                  13,000 +
                </Text>
                <Text textAlign="center">Verified users</Text>
              </Box>
            </SimpleGrid>
          </Container>
        </Flex>
      </Box>

      <Testimonials />

      <Footer />

      <FloatingButton />
    </div>
  );
}
