import React from "react";
import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import {
  Stack,
  Heading,
  Container,
  Box,
  Text,
  VStack,
  HStack,
  ListIcon,
  ListItem,
  List,
  useColorModeValue,
  Button,
} from "@chakra-ui/react";
import { FaCheckCircle } from "react-icons/fa";
import { TickerTape, CryptoCurrencyMarket } from "react-ts-tradingview-widgets";
import FloatingButton from "../components/FloatingButton";
import { PriceWrapper } from "../components/Pricing";

function Plans() {
  return (
    <div>
      <Head>
        <title>Financial Plans - Expert Hub Trade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <TickerTape colorTheme="dark"></TickerTape>

      <Container maxW={"6xl"}>
        <Box py={12}>
          <VStack spacing={2} textAlign="center"></VStack>
          <Stack
            direction={{ base: "column", md: "row" }}
            textAlign="center"
            justify="center"
            spacing={{ base: 4, lg: 10 }}
            py={10}
            mt={10}
          >
            <PriceWrapper>
              <Box py={4} px={12}>
                <Text fontWeight="500">Basic Plan</Text>
                <HStack justifyContent="center">
                  <Text> $300 - $999</Text>
                </HStack>
              </Box>
              <VStack
                bg={useColorModeValue("gray.50", "gray.700")}
                py={4}
                borderBottomRadius={"xl"}
              >
                <List spacing={3} textAlign="start" px={12}>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Daily Profit: %5.00
                  </ListItem>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Minimum Possible Deposit: $300
                  </ListItem>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Minimum Return: $510
                  </ListItem>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Duration: 2 Weeks
                  </ListItem>
                </List>
                <Box w="80%" pt={7}></Box>
              </VStack>
            </PriceWrapper>

            <PriceWrapper>
              <Box position="relative">
                <Box
                  position="absolute"
                  top="-16px"
                  left="50%"
                  style={{ transform: "translate(-50%)" }}
                >
                  <Text
                    // textTransform="uppercase"
                    bg={useColorModeValue("blue.300", "blue.700")}
                    px={3}
                    py={1}
                    color={useColorModeValue("gray.900", "gray.300")}
                    fontSize="sm"
                    // fontWeight="600"
                    rounded="xl"
                  >
                    Most Popular
                  </Text>
                </Box>
                <Box py={4} px={12}>
                  <Text>Silver Plan</Text>
                  <HStack justifyContent="center">
                    <Text>$1,000 - $4,999</Text>
                  </HStack>
                </Box>
                <VStack
                  bg={useColorModeValue("gray.50", "gray.700")}
                  py={4}
                  borderBottomRadius={"xl"}
                >
                  <List spacing={3} textAlign="start" px={12}>
                    <ListItem>
                      <ListIcon as={FaCheckCircle} color="green.500" />
                      Weekly Profit: %10.00
                    </ListItem>
                    <ListItem>
                      <ListIcon as={FaCheckCircle} color="green.500" />
                      Minimum Possible Deposit: $1,000
                    </ListItem>
                    <ListItem>
                      <ListIcon as={FaCheckCircle} color="green.500" />
                      Maximum Possible Deposit: $4,999
                    </ListItem>
                    <ListItem>
                      <ListIcon as={FaCheckCircle} color="green.500" />
                      Minimum Return: $1,560
                    </ListItem>
                    <ListItem>
                      <ListIcon as={FaCheckCircle} color="green.500" />
                      Maximum Return: $7,798
                    </ListItem>
                    <ListItem>
                      <ListIcon as={FaCheckCircle} color="green.500" />
                      Duration: 1 Month
                    </ListItem>
                  </List>
                </VStack>
              </Box>
            </PriceWrapper>
            <PriceWrapper>
              <Box py={4} px={12}>
                <Text>Gold Plan</Text>
                <HStack justifyContent="center">
                  <Text>$5,000 - $9,999</Text>
                </HStack>
              </Box>
              <VStack
                bg={useColorModeValue("gray.50", "gray.700")}
                py={4}
                borderBottomRadius={"xl"}
              >
                <List spacing={3} textAlign="start" px={12}>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Monthly Profit: %8.00
                  </ListItem>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Minimum Possible Deposit: $5,000
                  </ListItem>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Maximum Possible Deposit: $9,999
                  </ListItem>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Minimum Return: $9,200
                  </ListItem>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Maximum Return: $18,398
                  </ListItem>
                  <ListItem>
                    <ListIcon as={FaCheckCircle} color="green.500" />
                    Duration: 3 Months
                  </ListItem>
                </List>
              </VStack>
            </PriceWrapper>
          </Stack>
        </Box>
      </Container>

      <FloatingButton />
      <Footer />
    </div>
  );
}

export default Plans;
